version: '3.4'

services:
  startingfilesblogwithusersstart:
    image: startingfilesblogwithusersstart
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
      - 5000:5000
